config/routes.rb
Rails.application.routes.draw do
  resources :sizes
  resources :types
  resources :menus
  resources :orders
  
  root 'pages#home'

  get 'orders/new'
  get 'orders/create'
  get 'orders/update'
  get 'orders/edit'
  get 'orders/destroy'
  get 'orders/index'
  get 'orders/show'
  get 'menus/new'
  post 'menus/create'
  put 'menus/update'
  get 'menus/edit'
  delete 'menus/destroy'
  get 'menus/index'
  get 'menus/show'
  get 'sizes/new'
  post 'sizes/create'
  put 'sizes/update'
  get 'sizes/edit'
  delete 'sizes/destroy'
  get 'sizes/index'
  get 'sizes/show'
  get 'types/new'
  post 'types/create'
  put 'types/update'
  get 'types/edit'
  delete 'types/destroy'
  get 'types/index'
  get 'types/show'
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :type
  belongs_to :size

  validates :name, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :menu

  validates :qty, presence: true
end

app/models/size.rb
class Size < ActiveRecord::Base
	validates :name, presence: true
end

app/models/type.rb
class Type < ActiveRecord::Base
	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def index
    @menus = Menu.all
  end

  def show
  end

  private

    def set_menu
      @menu = Menu.find(params[:id])
    end

    def menu_params
      params.require(:menu).permit(:name, :price, :type_id, :size_id)
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sizes_controller.rb
class SizesController < ApplicationController

  before_action :set_size, only: [:show, :update, :edit, :destroy]

  def new
    @size = Size.new
  end

  def create
    @size = Size.new(size_params)

    respond_to do |format|
      if @size.save
        format.html { redirect_to @size, notice: 'Size was successfully created.' }
        format.json { render :show, status: :created, location: @size }
      else
        format.html { render :new }
        format.json { render json: @size.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @size.update(size_params)
        format.html { redirect_to @size, notice: 'Size was successfully updated.' }
        format.json { render :show, status: :ok, location: @size }
      else
        format.html { render :edit }
        format.json { render json: @size.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def destroy
    @size.destroy
    respond_to do |format|
      format.html { redirect_to sizes_url, notice: 'Size was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def index
    @sizes = Size.all
  end

  def show
  end

  private

    def set_size 
      @size = Size.find(params[:id])
    end

    def size_params
      params.require(:size).permit(:name)
    end

end

app/controllers/types_controller.rb
class TypesController < ApplicationController

  before_action :set_type, only: [:show, :edit, :update, :destroy]

  def new
    @type = Type.new
  end

  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end

  end

  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def index
    @types = Type.all
  end

  def show
  end

  private
    
    def set_type
      @type = Type.find(params[:id])
    end

    def type_params
      params.require(:type).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheCoffeeShop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/menus/_form.html.erb
<%= simple_form_for(@menu) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.association :type %>
    <%= f.association :size %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/menus/create.html.erb
<h1>Menus#create</h1>
<p>Find me in app/views/menus/create.html.erb</p>

app/views/menus/destroy.html.erb
<h1>Menus#destroy</h1>
<p>Find me in app/views/menus/destroy.html.erb</p>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Menus</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Type</th>
      <th>Size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.name %></td>
        <td><%= menu.price %></td>
        <td><%= menu.type.name %></td>
        <td><%= menu.size.name %></td>
        <td><%= link_to 'Show', menu %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @menu.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @menu.price %>
</p>

<p>
  <strong>Type:</strong>
  <%= @menu.type.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @menu.size.name %>
</p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>

app/views/menus/update.html.erb
<h1>Menus#update</h1>
<p>Find me in app/views/menus/update.html.erb</p>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/orders/update.html.erb
<h1>Orders#update</h1>
<p>Find me in app/views/orders/update.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/sizes/_form.html.erb
<%= simple_form_for(@size) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sizes/create.html.erb
<h1>Sizes#create</h1>
<p>Find me in app/views/sizes/create.html.erb</p>

app/views/sizes/destroy.html.erb
<h1>Sizes#destroy</h1>
<p>Find me in app/views/sizes/destroy.html.erb</p>

app/views/sizes/edit.html.erb
<h1>Editing Size</h1>

<%= render 'form' %>

<%= link_to 'Show', @size %> |
<%= link_to 'Back', sizes_path %>

app/views/sizes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sizes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sizes.each do |size| %>
      <tr>
        <td><%= size.name %></td>
        <td><%= link_to 'Show', size %></td>
        <td><%= link_to 'Edit', edit_size_path(size) %></td>
        <td><%= link_to 'Destroy', size, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Size', new_size_path %>

app/views/sizes/new.html.erb
<h1>New Size</h1>

<%= render 'form' %>

<%= link_to 'Back', sizes_path %>

app/views/sizes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @size.name %>
</p>

<%= link_to 'Edit', edit_size_path(@size) %> |
<%= link_to 'Back', sizes_path %>

app/views/sizes/update.html.erb
<h1>Sizes#update</h1>
<p>Find me in app/views/sizes/update.html.erb</p>

app/views/types/_form.html.erb
<%= simple_form_for(@type) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/types/create.html.erb
<h1>Types#create</h1>
<p>Find me in app/views/types/create.html.erb</p>

app/views/types/destroy.html.erb
<h1>Types#destroy</h1>
<p>Find me in app/views/types/destroy.html.erb</p>

app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.name %></td>
        <td><%= link_to 'Show', type %></td>
        <td><%= link_to 'Edit', edit_type_path(type) %></td>
        <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New Type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @type.name %>
</p>

<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>

app/views/types/update.html.erb
<h1>Types#update</h1>
<p>Find me in app/views/types/update.html.erb</p>